spring:
  mail:
    host: smtp.163.com
    username: nvj335537@163.com
    password: EDEUKSDOTYFZSOWD
  rabbitmq:
    addresses: 172.19.190.157
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefg
      expire: 7
  datasource:
    url: jdbc:mysql://172.19.190.157:3306/springboot
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
  minio:
    endpoint: http://172.19.190.157:9000
    username: minio
    password: password

  data:
    redis:
      host: 172.19.190.157
=======
>>>>>>> parent of 5adba83 (头像上传操作完成)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

